_BASE_: "${CODE}/detectron2/projects/UniDet/configs/Base-CRCNN-COCO.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p67_resnest_fpn_backbone"
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
  RESNETS:
    DEPTH: 200
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "BN"
  FPN:
    NORM: "BN"
  WEIGHTS: "$CODE/detectron2/weights/Unified_learned_OCI_RS200_6x.pth"
  META_ARCHITECTURE: "UnifiedRCNN"
  ROI_HEADS:
    NUM_CLASSES: 701
    NAME: "UnifiedCascadeROIHeads"
  ROI_BOX_HEAD:
    USE_SIGMOID_CE: True
    HIERARCHY_IGNORE: True
    HIERARCHY_POS_PARENTS: True
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "BN"
INPUT:
  FORMAT: "RGB"
DATASETS:
  TRAIN: ("coco_2017_train","objects365_train","oid_train",)
  TEST: ('coco_2017_val','oid_val_expanded','objects365_val',)
DATALOADER:                                                                                                                                                                                                                                                                                                                                                                 
  SAMPLER_TRAIN: "MultiDatasetSampler"
  NUM_WORKERS: 1
MULTI_DATASET:
  ENABLED: True
  DATASETS: ['coco', 'objects365', 'oid']
  NUM_CLASSES: [80, 365, 500]
  DATA_RATIO: [1, 1, 1]
  USE_CAS: [False, True, True]
  UNIFIED_LABEL_FILE: '$CODE/detectron2/datasets/label_spaces/kitchen_mAP+M.json'
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (480000, 500000)
  MAX_ITER: 540000
  CHECKPOINT_PERIOD: 120000
